"""领域模型包。"""

from __future__ import annotations

from src.domain.models.candidates import (
    Candidate,
    CandidateBase,
    ContextCandidate,
    PlaceCandidate,
    StayCandidate,
    TransportCandidate,
)
from src.domain.models.constraint import (
    Constraint,
    ConstraintSnapshot,
    ConstraintSource,
    ConstraintValue,
)
from src.domain.models.enums import (
    ConstraintHardness,
    ErrorCategory,
    EvidenceStatus,
    InteractionMode,
    IssueSeverity,
    WorkflowStatus,
)
from src.domain.models.evidence import EvidenceItem, EvidenceSnapshot, EvidenceValue
from src.domain.models.itinerary import (
    BudgetBreakdown,
    BudgetLine,
    ItineraryDay,
    ItineraryPlan,
    PlanAlternative,
    PlanBuffer,
    PlanItem,
)
from src.domain.models.trip_request import (
    BudgetSemantics,
    BudgetSpec,
    TravelerProfile,
    TripRequest,
)
from src.domain.models.validation import ValidationGate, ValidationIssue
from src.domain.models.value_objects import (
    CandidateId,
    CheckpointId,
    ConstraintId,
    DateRange,
    EvidenceId,
    GeoPoint,
    IssueId,
    Money,
    PlanId,
    PlanItemId,
    RequestId,
    SessionId,
    StableId,
    TraceId,
    TripId,
)

__all__ = [
    "BudgetBreakdown",
    "BudgetLine",
    "BudgetSemantics",
    "BudgetSpec",
    "Candidate",
    "CandidateBase",
    "CandidateId",
    "CheckpointId",
    "Constraint",
    "ConstraintHardness",
    "ConstraintId",
    "ConstraintSnapshot",
    "ConstraintSource",
    "ConstraintValue",
    "ContextCandidate",
    "DateRange",
    "ErrorCategory",
    "EvidenceId",
    "EvidenceItem",
    "EvidenceSnapshot",
    "EvidenceStatus",
    "EvidenceValue",
    "GeoPoint",
    "InteractionMode",
    "IssueId",
    "IssueSeverity",
    "ItineraryDay",
    "ItineraryPlan",
    "Money",
    "PlaceCandidate",
    "PlanAlternative",
    "PlanBuffer",
    "PlanId",
    "PlanItem",
    "PlanItemId",
    "RequestId",
    "SessionId",
    "StableId",
    "StayCandidate",
    "TraceId",
    "TransportCandidate",
    "TravelerProfile",
    "TripId",
    "TripRequest",
    "ValidationGate",
    "ValidationIssue",
    "WorkflowStatus",
]
